Zoomin/Zoomin/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from .decorators import staff_required
from accounts import views

admin.site.login = staff_required(admin.site.login)

urlpatterns = [

    url('admin/', admin.site.urls),

    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^blog/$',views.AboutView.as_view(),name='blog'),
    url(r'^account/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include("django.contrib.auth.urls")),
    url(r'posts/',include('posts.urls',namespace='posts')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Zoomin/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/', auth_views.LoginView.as_view(template_name="registration/login.html"),name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(), name="logout"),
    url(r'^signup/', views.Signup.as_view(), name="signup"),
]

Zoomin/posts/urls.py
from django.conf.urls import url
from posts import views

app_name = 'posts'

urlpatterns = [
    url(r'^gallery/$',views.display_images,name='display'),
    url(r'^newposts/$',views.NewPost.as_view(),name='post'),
]

Zoomin/accounts/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone

class User(auth.models.User,auth.models.PermissionsMixin):


    def __str__(self):
        return '@{}'.format(self.username)

        

Zoomin/posts/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Newpost(models.Model):

    name = models.CharField(max_length=200,unique=True)
    new_photo = models.ImageField(upload_to='posts/images', blank=True)

    def get_absolute_url(self):
        return reverse('index')

    def __str__(self):
        return self.name

Zoomin/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateform(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email'
        self.fields['password1'].label = 'Password'
        self.fields['password2'].labels = 'Confirm Password'

Zoomin/posts/forms.py
from django import forms
from posts.models import Newpost

class Newpostform(forms.ModelForm):
    class Meta:
        model = Newpost
        fields = '__all__'

Zoomin/accounts/views.py
from django.contrib.auth import login,logout
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import Http404
from functools import wraps
from django.views.generic import TemplateView,CreateView
from . import forms

class IndexView(TemplateView):
    template_name = 'index.html'

class AboutView(TemplateView):
    template_name = 'blog.html'

class Signup(CreateView):
    form_class = forms.UserCreateform
    success_url = reverse_lazy("login")
    template_name = 'registration/signup.html'

def staff_required(func):
    @wraps(func)
    def wrapper(request, *args, **kwargs):
        if request.user.is_superuser:
            return func(request, *args, **kwargs)
        raise Http404()
    return wrapper

Zoomin/posts/views.py
from django.shortcuts import render
from posts.models import Newpost
from posts.forms import Newpostform
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic import CreateView
# Create your views here.


class NewPost(CreateView):
    model = Newpost
    fields = ['new_photo']
    def newpost(request):

        registered = False

        if user.is_superuser:

            if request.method == 'POST':
                New_post = Newpostform(data=request.POST)

                if New_post.is_valid():
                    post = New_post.save(commit=False)

                    if 'new_photo' in request.FILES:
                        print('found it')
                        post.New_post = request.FILES['new_photo']

                    New_post.save()

                    registered = True
                else:
                    print(Newpostform.erros)
            else:
                New_post = Newpostform
        return render(request,'posts/newpost_form.html',{'New_post : Newpostform'})


def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'registration/login.html', {})

def display_images(request):

    if request.method == 'GET':

        Images = Newpost.objects.all()
        return render(request,'posts/display.html',{'images':Images})

Zoomin/posts/templates/posts/display.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-welcome">
  <h3 id='gallery'>Gallery</h3>
  <hr class='horizontal'>
  <div class="jumbotron jumbotron-welcome">
    <div class="row">
    {% for post in images %}
            <div class="col-lg-4 col-6 ">
              <img src="{{ post.new_photo.url }}" class="img-thumbnail img-fluid" />
            </div>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

Zoomin/posts/templates/posts/newpost_form.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron account">
  <h3>New Post</h3>
  <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-success' value="upload">
  </form>
</div>
{% endblock %}

Zoomin/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Zoomin Photography</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>
  <body class="Body">
        <nav id='navbar_top' class='navbar navbar-expand-md navbar-light bg-secondary'>
          <a class='navbar-brand py-2 bigbrand'href="{% url 'index' %}"><span class='fa fa-home'></span> __.Zoomin_Photography.__ </a>
          <hr>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id='navbarTogglerDemo01'>
            <hr>
            <a class='nav-item nav-link py-2 blog'href="{% url 'blog' %}">  Blog  </a>
            <hr>
            <a class='nav-item nav-link py-2 blog' href="{% url 'posts:display' %}">  Gallery </a>
<!--            {% if user.is_superuser %} -->
            <hr>
            <a class='nav-item nav-link py-2 blog'href="{% url 'posts:post' %}">Posts</a>
<!--            {% else %}
            {% endif %} -->
            <hr>
              <div class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <div class="container">
                <div class="dropdown">
                    <button class="btn btn-default btn-md dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                      Account
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                        <p class='dropdown-item py-0'>Welcome {{user.username}}!</p>
                        <a class="dropdown-item py-0" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                  </div>
                </div>
                <hr>
                  <a class="nav-item nav-link py-1"href="mailto:zoominphotography1701@gmail.com"> <span class='fa fa-envelope'></span></a> <hr>
                  <a class="nav-item nav-link py-0"href="https://www.instagram.com/__.zoomin_photography.__/" target='blank'><img id='insta-logo' src="{% static 'images/insta.png'%}" alt="insta"></a>
<!--                <div class="container">
                  <div class="dropdown">
                    <button class="btn btn-default btn-md dropdown-toggle" type="button" id="ContactButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      contact
                    </button>
                    <div class="dropdown-menu" aria-labelledby="ContactButton">
                      <div class="contact">
                        <a class="dropdown-item py-0"href="mailto:zoominphotography1701@gmail.com"><span class='fa fa-envelope'></span></a>
                        <a class="dropdown-item py-0"href="https://www.instagram.com/__.zoomin_photography.__/" target='blank'><img id='insta-logo' src="{% static 'images/insta.png'%}" alt="insta"></a>
                      </div>

                    </div>  -->
                  </div>
                </div>

                {% else %}
                <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                {% endif %}
              </div>



            </div>
        </nav>
        <div class="container">

           {% block content %}

           {% endblock %}

         </div>
    </div>







    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


  </body>
</html>

Zoomin/templates/blog.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-welcome">
  <p class='blog-page'>Mobile photography means taking pictures with a mobile camera.
  The camera technology on smartphones is more than adequate for taking photos and publishing them online.
  Depending on the camera quality and number of pixels, photos can be printed 8x10" and higher with excellent results.
  The significant difference today is that everyone with a smartphone has a camera handy.
  The following table shows the minimum number of megapixels (MPs) required for quality printing.
  Megapixels are only a base requirement; however, the quality of the camera's optics and digital processing varies from model to model.
  See megapixel and digital camera.</p>
  <p class='blog-page'>Your phone camera is your best camera, because it's always with you.
  When people say this about mobile photography, or iphoneography as it's also called, they're usually talking about snapping those unexpected moments:
  a man in a banana suit on his way to work; a celebrity involved in a punch-up; or maybe just a beautiful sunset.
  Certainly, mobile photographers are much more prolific than average amateur "big camera" enthusiasts.
  They have their photographic brains switched on all the time, looking for possibilities.
  And the ubiquity of these cameras, combined with their unobtrusiveness, have made them particularly effective at capturing candid moments in public spaces.
  But, for many, the initial snap is just the start. It's the raw material for a new creative process. Most mobile phone cameras take very dull photos.
  But it doesn't matter, because there are hundreds of apps to help you turn them into something amazing.
  And that's what's really at the heart of it. Costing pennies, mobile photography apps give you the creative power of Photoshop, and more besides, without being tied to your desk.
  This makes mobile photography incredibly liberating for the creative photographic spirit.
  Suddenly, every free moment is an opportunity to both take and craft images.
  These apps have accelerated the creative process, as well as allowing you, quite simply, to be more creative, more of the time, for less money</p>
  <ol class='jumbotron tips'>
      <p><strong>TIPS:</strong></p>

      <li><strong>Use gridlines to balance your shot.</strong></li>
      <li><strong>Set your camera's focus.</strong></li>
      <li><strong>Focus on one subject.</strong></li>
      <li><strong> Embrace negative space.</strong></li>
      <li><strong>Avoid zooming in.</strong></li>
      <li><strong>Use natural light.</strong></li>
      <li><strong>Set your camera app's exposure manually.</strong></li>
      <li><strong>Clean your phone's lens.</strong></li>
      <li><strong>Don't be afraid to edit.(recommended:lightroom)</strong></li>

    </ol>


</div>
{% endblock %}

Zoomin/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron jumbotron-welcome">
  <h3 id='welcome'>Welcome to Zoomin Photography</h3>
  <p id='contactinformation'><a href="{% url 'posts:display' %}">View more on gallery</a></p>
    {% if user.is_authenticated %}
    {% else %}
    <p id='contactinformation'>(Login for Contact Information)</p>
    {% endif %}
  <hr class='horizontal'>
<div class="jumbotron jumbotron-welcome">
  <div class="row">
    <div class="col-lg-4 col-6 "><img class="img-thumbnail img-fluid"src='/static/images/30.jpg' alt="one"</img></div>
    <div class="col-lg-4 col-6 "><img class="img-thumbnail img-fluid"src="/static/images/44.jpg" alt="two"</img></div>
    <div class="col-lg-4 col-6 "><img class="img-thumbnail img-fluid"src="/static/images/49.jpg" alt="two"</img></div>
    <div class="col-lg-4 col-6 "><img class="img-thumbnail img-fluid"src='/static/images/7.jpg' alt="one"</img></div>
    <div class="col-lg-4 col-6 "><img class="img-thumbnail img-fluid"src="/static/images/27.jpg" alt="two"</img></div>
    <div class="col-lg-4 col-6 "><img class="img-thumbnail img-fluid"src="/static/images/26.jpg" alt="two"</img></div>

  </div>
</div>
</div>





{% endblock %}

Zoomin/templates/navbar.html
<!--    <nav class="navbar navbar-expand-lg navbar-transparent bg-transparent">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="container-fluid">
          <div class="navbar-nav ">
            <a class="navbar-brand bigbrand" href="{% url 'index' %}">Zoomin Photography</a>
            <a class="nav-item nav-link "href="{% url 'blog' %}">Blog</a>
          </div>
            <div class="navbar-nav align-right">
              {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="#"><span class="fa fa-user"></span></a>
              <p class='nav-item nav-link'>Welcome {{user.username}}!</p>
              <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              <a class='nav-item nav-link' href="mailto:pradeepravi17301@gmai.com"><span class='fa fa-envelope'></span></a>
              <a class='nav-item nav-link' href="https://www.instagram.com/__.zoomin_photography.__/" target='blank'><img id='insta-logo' src="static/images/insta.png" alt="insta"></a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
              {% endif %}

          </div>
        </div>
    </nav> -->



<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="static/css/master.css">
  </head>
  <body class-'body'>
    <nav class='navbar navbar-expand-md navbar-light bg-light'>
      <a class='navbar-brand bigbrand' href='#'>zoomin_photography</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id='navbarTogglerDemo01'>
        <a class='nav-item nav-link' href='#'>Blog</a>
          <div class="navbar-nav ml-auto">
            <a class='nav-item nav-link'>Welcome</a>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                contact
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Mail</a>
                <a class="dropdown-item" href="#">Insta</a>
              </div>
            </div>
        </div>
      </div>

    </nav>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>









<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand bigbrand" href="{% url 'index' %}">Zoomin Photography</a>
  <a class="nav-item nav-link "href="{% url 'blog' %}">Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id='navbarTogglerDemo01'>
        <div class="navbar-nav ml-auto ">
<!--                <div class="navbar-nav align-right">  -->
              {% if user.is_authenticated %}
<!--                <a class="nav-item nav-link" href="#"><span class="fa fa-user"></span></a>  -->
                <p class='nav-item nav-link'>Welcome {{user.username}}!</p>
                <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                <a class='nav-item nav-link' href="mailto:pradeepravi17301@gmai.com"><span class='fa fa-envelope'></span></a>
                <a class='nav-item nav-link' href="https://www.instagram.com/__.zoomin_photography.__/" target='blank'><img id='insta-logo' src="{% static 'images/insta.png'%}" alt="insta"></a>
              {% else %}
  <!--          </div>  -->

              <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
              {% endif %}
          </div>
        </div>
    </div>


    </nav>